name: Snowflake Connection Test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: '実行対象の環境を選択してください'
        type: environment # これにより Environment の一覧がドロップダウンになります
        required: true
        default: 'test'
        
permissions:
  id-token: write # OIDCトークン生成に必須
  contents: read

jobs:
  test-connection:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_AUTHENTICATOR: 'https://token.actions.githubusercontent.com'
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v.2.0.1
        with:
          cli-version: "3.14.0"
          use-oidc: true

      - name: Create Snowflake Config
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/config.toml
          [connections.github_connection]
          account = "<% env.SNOWFLAKE_ACCOUNT %>"
          user = "<% env.SNOWFLAKE_USER %>"
          authenticator = "<% env.SNOWFLAKE_AUTHENTICATOR %>"
          role = "<% env.SNOWFLAKE_ROLE %>"
          warehouse = "<% env.SNOWFLAKE_WAREHOUSE %>"
          EOF
          chmod 600 ~/.snowflake/config.toml
          
      - name: Execute SQL via Snowflake CLI
        run: |
            snow sql -q "SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();" --connection "github_connection"
