name: Snowflake Connection Test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: '実行対象の環境を選択してください'
        type: environment # これにより Environment の一覧がドロップダウンになります
        required: true
        default: 'test'
        
permissions:
  id-token: write # OIDCトークン生成に必須
  contents: read

jobs:
  test-connection:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v.2.0.1
        with:
          cli-version: "3.14.0"
          use-oidc: true

      - name: Execute SQL via Snowflake CLI
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_AUTHENTICATOR: 'https://token.actions.githubusercontent.com'
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snow sql -q "SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();"

