name: Snowflake Connection Test
on: [workflow_dispatch] # 手動実行用

permissions:
  id-token: write # OIDCトークン生成に必須
  contents: read

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SQL
        uses: snowflake-computing/snowflake-cli-action@v2.0.1
        with:
          container-options: "-e SNOWFLAKE_AUTHENTICATOR='https://token.actions.githubusercontent.com'"
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          run-cli-command: "sql -q 'SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();'"
